# Generated by Django 4.2.7 on 2025-10-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, verbose_name='Matricula')),
                ('clave_materia', models.CharField(max_length=10, verbose_name='Clave Materia')),
                ('c1', models.CharField(max_length=10, verbose_name='calificacion 1')),
                ('c2', models.CharField(max_length=10, verbose_name='calificacion 2')),
                ('final', models.CharField(max_length=10, verbose_name='final')),
                ('especial', models.CharField(max_length=10, verbose_name='extra')),
            ],
        ),
        migrations.CreateModel(
            name='materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_materia', models.CharField(max_length=10, verbose_name='Clave Materia')),
                ('materia', models.CharField(max_length=50, verbose_name='Nombre Materia')),
                ('cuatrimestre', models.CharField(max_length=20, verbose_name='Cuatrimestre')),
                ('creditos', models.CharField(max_length=10, verbose_name='Creditos')),
            ],
        ),
    ]
