# Generated by Django 4.2.7 on 2025-10-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, verbose_name='Matricula')),
                ('cuatrimestre', models.CharField(max_length=20, verbose_name='Cuatrimestre')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre alumno')),
                ('paterno', models.CharField(max_length=40, verbose_name='Paterno')),
                ('materno', models.CharField(max_length=40, verbose_name='Materno')),
                ('estatus', models.CharField(max_length=20, verbose_name='Matricula')),
            ],
        ),
    ]
