# Generated by Django 4.2.7 on 2025-10-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='estatus',
            field=models.CharField(max_length=20, verbose_name='estatus'),
        ),
    ]
