# Generated by Django 4.2.7 on 2025-10-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, verbose_name='Nombre Usuario')),
                ('paterno', models.CharField(max_length=40, verbose_name='Paterno')),
                ('materno', models.CharField(max_length=40, verbose_name='Materno')),
                ('estatus', models.CharField(max_length=40, verbose_name='Estatus')),
                ('usuario', models.CharField(max_length=10, verbose_name='usuario')),
                ('clave', models.CharField(max_length=10, verbose_name='contrasena')),
            ],
        ),
    ]
